### ISSUE TITLE
Infinite EXP Bug

### ISSUE THREAD

**Issue by zlAquiles** [Zrips/BottledExp#26]
By using /bottle store max, when you put the exp bottle in your left hand and throw the bottle, when you grab the exp it gives you a percentage more, by doing this many times you can increase your exp very quickly, that doesn't happen if you you do with the main hand

Version:
![image](https://user-images.githubusercontent.com/69038261/162559862-a2340660-aeac-439c-a15e-8422928844cb.png)
![imagen_2022-04-09_033218](https://user-images.githubusercontent.com/69038261/162559853-628a66fb-0512-4c39-b141-785459794368.png)

Config.yml
```
bottle:
  # Shows if there is available new version on login with bottledexp.versioncheck permission node
  ShowNewVersion: true
  # Language file you want to use
  Language: ES
  # How much player will spend converting his xp to bottles. This cant be lower than xpEarn
  xpCost: 10
  # How much player will get xp from xp bottle
  xpEarn: 10
  # Do you want to use custom items when converting xp to xp bottles
  useItems: false
  # Material name for custom item, by default its empty glass bottle
  consumedItemMaterial: GLASS_BOTTLE
  # How many to consume when converting. This is for every bottle you will get
  amountConsumed: 1
  # Do you want to charge money for xp conversion
  useMoney: false
  # How much it will gonna cost
  moneyCost: 100
  # Do you want to show extra information for how much its gonna cost to level up
  useBottleMoney: false
  # How much one xp bottle costs
  bottleCost: 3.25
  # Do you want to show exp consumed on enchant
  ShowEnchantExp: true
  # Do you want to show all enchantments player gets after enchanting item
  ShowEnchant: false
  # Do you want to use new 1.8 enchant system
  UseThreeButtonEnchant: true
  give:
    # How much exp will be lost during transfer in percentage
    LostDurringTransfer: 0
  BlockInteraction:
    Use: false
    # Do you want to use right click, if false then left will be used, good for block with interactions like enchant table
    UseRightClick: false
    # Material of block will be used to convert xp to bottles
    BlockMaterial: ENCHANTING_TABLE
    # Material of item in hand when you want to convert xp by clicking block
    HandItemMaterial: GLASS_BOTTLE
    # How many bottles to give everytime
    GiveEveryTime: 1
    # How many times to multiply given bottles by clicking shift
    Multiplayer: 10
  CustomBlockInteraction:
    Use: false
    # Do you want to use right click, if false then left will be used, good for block with interactions like enchant table
    UseRightClick: false
    # Material of item in hand when you want to convert xp by clicking block
    HandItemMaterial: GLASS_BOTTLE
    # How many bottles to give everytime
    GiveEveryTime: 1
    # How many times to multiply given bottles by clicking shift
    Multiplayer: 10
  CraftExpContainer:
    # When this set to true there will be option to craft special expbottle by placing empty glass bottle into crafting
    # You can consume it by right clicking it
    Use: false
  # When this set to true, all trades with villgers involving exp will be disabled
  DisableVillagerExpTrade: false
  # When this set to true,destrying mob spawners wont drop exp
  DisableMobSpawnerExp: false

```
