### ISSUE TITLE
Cost inferior to 1 are rounded to 0

### ISSUE THREAD

**Issue by Bibithom** [Zrips/BottledExp#31]
Hi, 
I wuld like to be able to charge 0.08 $ per bottle, but prices are rounded to zero when converting few bottles.
I'm using vault and cmi for my economy.
There is my bottledexp's config (only economy values):

```yaml
  # Do you want to charge money for xp conversion
  useMoney: true
  # How much it will gonna cost
  moneyCost: 0.08
  # Do you want to show extra information for how much its gonna cost to level up
  useBottleMoney: true
  # How much one xp bottle costs
  bottleCost: 0.08
```
BottledExp verison : 3.1.1.0
Cmi : 8.2.5.3 (with vault provided)

There's a screen to show what going on (sorry it's in french)
![bottle_conversion](https://user-images.githubusercontent.com/18242631/203551372-0a77d4b6-1c0b-4d70-8322-cd1efa017848.png)
